# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03b509b4c9a9d89b5357f01f565961de52b41314fbac6d5dc803896f6c3f4c930526a52bf0a544fc4689cdce92759e7a8ea16fa5a3109defb4488c3f597187bd

test:
  secret_key_base: 0ebb25705339b92ec00ea3f330057bd91f104cd6070995e873e09f453a15a001e4f1b7c1713c16b0ae9426b807a18ff4eed530436a875883bfb0735881c7ecb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
